// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	Starting_objectives = 0,
	Next_Level = 1,
	Apartment_Blues = 2,
	Ordering_Chinese = 3,
	Bequeathing = 4,
	Chinese_is_here = 5,
	Fortune_Cookie = 6,
	Fortune_1 = 7,
	Fortune_2 = 8,
	Fortune_3 = 9,
	Fortune_4 = 10,
	Fortune_5 = 11,
	Fortune_6 = 12,
}
