// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	Starting_objectives = 0,
	Next_Level = 1,
	Apartment_Blues = 2,
	Ordering_Chinese = 3,
	Bequeathing = 4,
}
